export type User {
  nickname: string;
  firstname?: string;
  lastname?: string;
  password: string;
  salt: string;
  created_at: Date;
  updated_at: Date | null;
  deleted_at: Date | null;
  role: 'user' | 'moderator' | 'admin';
}

type Query {
  # getUsers: [User!]!
  # getUserByNickname(nickname: String!): User
  ping: String
}

type Mutation {
  addUser(user: PostUserInput!): String!
  deleteUser(userId: ID!): String!
  updateUser(user: UpdateUserInput!): String!
}

input PostUserInput {
  name: String!
  nickname: String!
  email: String!
}

input UpdateUserInput {
  userId: ID!
  name: String
  nickname: String
  email: String
}
